spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maverick_movie?createDatabaseIfNotExist=true
    password: 332003
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: MaverickMovie
  jpa:
    database: mysql
server:
  port: 4242